# Generated by Django 5.2.16 on 2026-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sitter_pet_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
