# Generated by Django 5.2.16 on 2026-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_looking_for',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_pets',
            field=models.BooleanField(default=True),
        ),
    ]
