# Generated by Django 5.2.16 on 2026-07-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_availability'),
        ('accounts', '0008_add_notification_preferences'),
    ]

    operations = [
    ]
