# Generated by Django 5.2.17 on 2026-08-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_actor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_connection', 'New Connection'), ('new_message', 'New Message'), ('message_deleted', 'Message Deleted'), ('booking_request', 'Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('new_review', 'New Review'), ('new_comment', 'New Comment'), ('new_like', 'New Like')], max_length=50),
        ),
    ]
